
```{r setup}
#| include: false
primary = "#002145"
secondary = "#6495ed"
tertiary = "#ffa319"
fourth_color = "#DB0B5B"
suppressMessages(library(tidyverse))
theme_set(
  theme_bw() + 
    theme(
      plot.background = element_blank(), 
      legend.background = element_blank(),
      legend.key = element_blank()
    )
)
lighten_colour <- function(color_hex, strength = 0.7) {
  stopifnot(strength >= 0 && strength <= 1)
  color_rgb <- col2rgb(color_hex)[, 1]
  color_rgb <- (1 - strength) * color_rgb + strength * 255
  rgb(color_rgb[1], color_rgb[2], color_rgb[3], maxColorValue = 255)
}
```

```{r, dev.args=list(bg="#002145")}
#| include: false
#| label: cover-art
#| fig-width: 8
#| fig-height: 4.5
library(dpf)
data(tempos)
pvec_ml <- read_rds("data/pvec_ml.rds") |>
  select(-value,-fevals,-gevals,-convergence) |>
  data.matrix() |> 
  data.frame()
source("src/dirichlet_precision.R")
cols <- RColorBrewer::brewer.pal(9, "Blues")
tempos |>
  select(-meas_num, -beat) |>
  pivot_longer(-note_onset) |>
  ggplot() +
  geom_line(
    aes(note_onset, value, color = as.numeric(as.factor(name)), group = name)
  ) +
  coord_cartesian(xlim = c(2, 44)) +
  scale_x_continuous(expand = expansion()) +
  scale_y_continuous(expand = expansion()) +
  theme_void() +
  #scale_colour_manual(values = rep(cols, length.out = ncol(tempos) - 3)) +
  scale_color_distiller(palette = "Set1", direction = 1) +
  theme(legend.position = "none")
```


```{r qrcodes, fig.width=8, fig.height=4, dev="png"}
#| include: false
qrdat <- function(text, ecl = c("L", "M", "Q", "H")) {
  x <- qrcode::qr_code(text, ecl)
  n <- nrow(x)
  s <- seq_len(n)
  tib <- tidyr::expand_grid(x = s, y = rev(s))
  tib$z <- c(x)
  tib
}

allqr <- bind_rows(
  slides = qrdat("https://dajmcdon.github.io/hmms-chopin-2025/"),
  paper = qrdat("http://dx.doi.org/10.1214/21-AOAS1457"), 
  `my www` = qrdat("https://dajmcdon.github.io", "Q"), .id = "site")

ggplot(allqr, aes(x, y, fill = z, alpha = z)) +
  geom_raster() +
  coord_equal(expand = FALSE) +
  scale_fill_manual(values = c("white", primary), guide = "none") +
  scale_alpha_manual(values = c(0, 1), guide = "none") + 
  theme_void() +
  facet_wrap(~ site, nrow = 1) +
  theme(
    text = element_text(
      color = primary, size = 36,
      margin = margin(3,0,3,0))
  )
```

